[general]
import = ["~/.config/alacritty/themes/active.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 16.0
normal = { family = "Cascadia Code NF", style = "SemiBold Italic" }
bold = { family = "Cascadia Code NF", style = "Bold" }
italic = { family = "Cascadia Code NF", style = "Italic" }
bold_italic = { family = "Cascadia Code NF", style = "Bold Italic" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1.00
startup_mode = "Maximized"
padding = { x = 0, y = 0 }

[scrolling]
history = 5000
multiplier = 3

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"

# [bell]
# animation = "Ease"
# duration = 150
# color = "#ffffff"
# command = "None"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\\t"
save_to_clipboard = true

[[keyboard.bindings]]
key = "A"
mods = "Super|Shift"
command = { program = "$HOME/.config/alacritty/opacity.sh", args = ["-"] }

[[keyboard.bindings]]
key = "D"
mods = "Super|Shift"
command = { program = "$HOME/.config/alacritty/opacity.sh", args = ["+"] }
