[colors.primary]
background = "#1f1d2e"
foreground = "#e0def4"

[colors.normal]
black   = "#26233a"
red     = "#eb6f92"
green   = "#31748f"
yellow  = "#f6c177"
blue    = "#9ccfd8"
magenta = "#c4a7e7"
cyan    = "#ebbcba"
white   = "#e0def4"

[colors.bright]
black   = "#6e6a86"
red     = "#eb6f92"
green   = "#31748f"
yellow  = "#f6c177"
blue    = "#9ccfd8"
magenta = "#c4a7e7"
cyan    = "#ebbcba"
white   = "#e0def4"

[colors.cursor]
cursor = "#f4b8c6"
text = "#1f1d2e"

[colors.selection]
background = "#1f1d2e"
text = "#e0def4"
