[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#cba6f7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f28fad"
green   = "#b5e8b0"
yellow  = "#fae3b0"
blue    = "#b4befe"
magenta = "#d0a9ff"
cyan    = "#a6e9d5"
white   = "#f2f2f2"

[colors.cursor]
cursor = "#f5c2e7"
text = "#1e1e2e"

[colors.selection]
background = "#2f2f40"
text = "#cdd6f4"
